### ISSUE TITLE
What if the input examplar image is less than 127*127?

### ISSUE THREAD

**Issue by RyanCV** [bertinetto/siamese-fc#11]
Hi, the tracker needs to resize the examplar image to 127*127 and the next frame to 255*255, however, if I want to track small object (e.g. less than 32*32), do you  think is it possible? Or any hints on modifying the tracking code? Thanks.

**Comment by bertinetto** [comment]
Hi,
There is no need to modify the code.
If the object is smaller than 127x127 it will be simply upsampled to
127x127.
In my experience the tracker works *particularly* well at low resolutions
and with small objects, probably because in ImageNet Video (the training
set) many objects are very tiny.
Hope this helps.
