### ISSUE TITLE
Have downloaded your imdb_video.mat, cannot train

### ISSUE THREAD

**Issue by hedes1992** [bertinetto/siamese-fc#14]
I just used the [ imdb_video.mat](http://bit.ly/imdb_video) you supplyed to run the training phase.
But line 248-249 of the code [./training/experiment.m](https://github.com/bertinetto/siamese-fc/blob/master/training/experiment.m) need use the JPEG_dir to generate batches for training.
So I cannot use current code to do my own training if I just use the imdb_video.mat.
I think there need to generate batch using the video_video.mat

**Comment by boldjoel** [comment]
<img width="1421" alt="2016-12-08 12 27 31" src="https://cloud.githubusercontent.com/assets/15371409/22183443/50f3957e-e0b6-11e6-965b-767a06fb5a00.png">
I came across the similar issue. It seems we need to make move img to folder strictly same to the file generate the mat file. But I don't know how yet.

**Comment by bertinetto** [comment]
Hi,
`/path/to/ILVRC15/crops/` is only a dummy path placeholder that you should replace with your local path containing the curated dataset.

If you want to train from scratch you have to generate the Imagenet Video on your own unfortunately. Hopefully the guide we provide here [https://github.com/bertinetto/siamese-fc/tree/master/ILSVRC15-curation](url) . 
Using the `imdb_video.mat` that we provide only saves you from point 7 of the tutorial.

Sharing with everyone the curated dataset we created would be much more handy, but unfortunately we cannot because of the rules we agreed upon when downloading the original dataset.

Hope this clarifies things :)
