### ISSUE TITLE
on model update

### ISSUE THREAD

**Issue by gongbudaizhe** [bertinetto/siamese-fc#17]
Hi,

One interesting aspect of your work is that no model update is employed during tracking.  As the paper states: "We found that updating(the feature representation of) the exemplar online through simple strategies, such as linear interpolation, does not gain much performance and thus we keep it fixed."

So my question is,
1. How did you conduct your experiments on model update? Can you elaborate on that? 
2. Specifically, how did you extract the feature of target on later frames that is used for model update?
3. Is there any numerical results compared to without model update?

Thanks

**Comment by bertinetto** [comment]
Hi,
Thanks for your interest in our work.

At the time I have tried a rolling average strategy, similarly to the one used in most correlation filter papers. Results were only an epsilon better, probably because I have only tried 2 or 3 learning rates -.-

We have a paper in at CVPR'17 with more extensive evaluations. We will put it on arxiv and share the code very soon. However, we found that learning rates between 0.005 and 0.015 are a good choice.

Cheers,
Luca

**Comment by gongbudaizhe** [comment]
Wow! Can't wait to see your new work! I have checked your homepage now and then, espetially after CVPR'17 anounced its accepted paper list. Your work is both conceptually concise and inspiring. I really enjoy reading your paper. Keep going!

I have done some preliminary experiments using different learning rate.  It indeed works best when learning rate is smaller than 0.01. I will wait and see your new work for more extensive evaluations : )

Cheers,
Bily

**Comment by bertinetto** [comment]
Thanks ! Really appreciated!
