### ISSUE TITLE
element-wise label size is 15*15 in the code while 17*17 in the paper

### ISSUE THREAD

**Issue by NicoleWang** [bertinetto/siamese-fc#26]
In siamese-fc paper, after cross-correlation layer, the output is a 17*17 array which means that the element-wise label should be a 17*17 array too. But in the released code, I found out that the element-wise label size is 15*15. It's quite confused.

**Comment by jvlmdr** [comment]
The score map (and element-wise labels) has size 17x17 for a search region of size 255 pixels. However, to enable data augmentation, we instead use a search region of size `255-2*8 = 239` pixels. This reduces the size of the score map to 15x15, since the score map has stride 8 with respect to the search region.

**Comment by NicoleWang** [comment]
Got it. Thanks a lot ~
