### ISSUE TITLE
About xCorr layer 

### ISSUE THREAD

**Issue by chenfsjz** [bertinetto/siamese-fc#40]
function outputs = forward(obj, inputs, params)
            assert(numel(inputs) == 2, 'two inputs are needed');

            z = inputs{1}; % exemplar
            x = inputs{2}; % instance (search region)

            assert(ndims(z) == ndims(x), 'z and x have different number of dimensions');
            assert(size(z,1) <= size(x,1), 'exemplar z has to be smaller than instance x');
            
            
            %c->channel b->channel
            [wx,hx,cx,bx] = size(x);
            x = reshape(x, [wx,hx,cx*bx,1]);
            o = vl_nnconv(x, z, []);
            [wo,ho,co,bo] = size(o);
            assert(co==bx);
            outputs{1} = reshape(o, [wo,ho,bo,co]);
        end

 Before call vl_nnconv( x,z,[] ) to compute the score,  you reshape the x to [wx,hx,cx*bx,1], but after this operation, the shape of x is not the same with z，so I was confused that how can vl_nnconv can operate    reasonable.

**Comment by jvlmdr** [comment]
We use the "filter group" functionality of the `vl_nnconv()` function:

The function `vl_nnconv(x, f)` expects `x` to have size `[h, w, c, n]` and `f` to have size `[fh, fw, fc, k]`. If `fc` is not equal to `c`, then the filters `f` are interpreted as filter groups. In this case, it is necessary that `c = g * fc` where `g` is an integer and `g` divides `k` (the number of output channels). Then the 1st `g` output channels will use only the 1st `fc` input channels, the 2nd `g` output channels will use only the 2nd `fc` input channels, ...

We make use of this functionality to convolve each template with its corresponding search image. Specifically, we transform `x` from a batch of size `b` with `c` features into a batch of size 1 with `c*b` features. Then we treat `z` as a filter bank with `b` filters, where each filter depends on only `c` channels. Since `c` divides `c*b`, this results in a `b` groups, where each group has only 1 output. Finally it is necessary to reshape the output to move from a batch of size 1 with `b` channels to a batch of size `b` with 1 channel.

Hope this helps! It's difficult to explain without a whiteboard!

**Comment by chenfsjz** [comment]
@jvlmdr Thank you for your reply!  I have understand the main idea of the v1_nnconv(x,f). In your code,the shape of output of `vl_nnconv(x,z,[])` is `[wo,ho,co,bo]`, after reshape this outputs,it produces the result with shape [wo,ho,bo,co]. And in your paper, the specific shape is `[17x17x1xco]`,  `co` is the batch, and this will be used to compute the score map. Is that right?
